### ISSUE TITLE
Constructive Data Analysis -  Gerando valor ao negócio

### ISSUE THREAD

**Issue by jccorrea** [data-science-sorocaba/call-4-papers#5]
**Comment:**
Um jeito novo de trabalhar com análise de dados onde todo esforço e trabalho se concentram em usar Data Science, Big Data e Business Analytics sempre alinhado com a estratégia e objetivo do negócio.

**Duration:**
 20 min.

**Mini Bio:**

Especialista em Big Data e Business Analytics com mais 12 anos no mercado de TI.
Scrum Master interessado em pensamento ágil usando Lean, Kanban, Toyota TBP,TPS
Experiência na atuação com grandes consultorias e clientes de diversos segmentos ;areas de  administração, gestão de dados e informações de grandes corporações.
Minha dedicação é :
- Dar direcionamento para que Data Science seja unido estratégia de negócio para gerar valor
- Solucionar problemas complexos com a gestão de informações nas organizações. 

Background como DBA, Desenvolvedor,  e Analista de BI utilizando os principais frameworks e produtos disponíveis no mercado como Oracle, Microstrategy, Microsoft, IBM, SAP atuando em projetos e sustentação  de ambientes de produção em diversas empresas.

**Comment by renatogpires** [comment]
@jccorrea você tem alguma preferência de ordem?

**Comment by renatogpires** [comment]
@jccorrea bom, você ficou com a talk logo após o café. Se precisar, dá um toque no whatsapp e invertemos isso, beleza?
