### ISSUE TITLE
Introdução ao Processamento de Linguagem Natural com Python

### ISSUE THREAD

**Issue by fernandojvdasilva** [data-science-sorocaba/call-4-papers#6]
**Comment:**
Nesta apresentação vamos estudar um workflow básico de NLP, desde o pré-processamento até um exemplo de aplicação de aprendizado supervisionado.

**Duration:**
Aprox. 45 minutos.

**Mini Bio:**
Fernando Vieira da Silva é Coordenador do Curso de Pós Graduação/Especialização em Ciência de Dados na Facens. Possui Mestrado e atualmente é Doutorando em Ciência da Computação pelo IC/Unicamp, ambos na área de NLP.

Observação: o título da issue deve ser o título da atividade. Não esqueça de selecionar as labels no menu à direita.

**Comment by renatogpires** [comment]
Oi @fernandojvdasilva 

Podemos deixar essa talk para o próximo meetup? Eu percebi que ela será mais extensa, aí ficaria melhor para não estourarmos o tempo desse meetup.

Tudo bem?

**Comment by fernandojvdasilva** [comment]
Oi Renato!

Tranquilo cara! Obrigado por responder! Fica aí o talk para quando vocês quiserem encaixar!

Até mais!

Fernando.
